### ISSUE TITLE
P145 svd++公式有误

### ISSUE THREAD

**Issue by wbyouth** [pusuo/graphx_in_action#2]
145页svd++公式 svd项用户u的隐性变量与商品i的隐性变量应为乘法记号，书里写的是加法，这个公式是svd++的核心表达，建议更正。

**Comment by shijinkui** [comment]
> 145页svd++公式 svd项用户u的隐性变量与商品i的隐性变量应为乘法记号，书里写的是加法，这个公式是svd++的核心表达，建议更正。

hi, @wbyouth 
你是对的，谢谢指正。第二版会更正
http://faculty.cse.tamu.edu/huangrh/Spring16/papers_course/matrix_factorization.pdf
